
version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.0.0
  kubernetes: circleci/kubernetes@1.0.1
  aws-ecr: circleci/aws-ecr@6.8.2

workflows:
  deployment:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: circleci-kubernetes-docker-flask
          dockerfile: Dockerfile
          path: demo_app
          tag: ${CIRCLE_SHA1}