
version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.0.0
  kubernetes: circleci/kubernetes@1.0.1
  aws-ecr: circleci/aws-ecr@7.2.0

workflows:
  deployment:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: 773075230823.dkr.ecr.us-east-1.amazonaws.com
          repo: circleci-kubernetes-docker-flask
          dockerfile: Dockerfile
          path: demo_app
          tag: ${CIRCLE_SHA1}