version: 2.1
orbs:
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.4.0
  aws-ecr: circleci/aws-ecr@7.2.0

workflows:
  deployment:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: circleci-kubernetes-docker-flask
          repo: eks_orb_demo_app
          dockerfile: Dockerfile
          path: demo_app
          tag: ${CIRCLE_SHA1}