version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  deploy-application:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      docker-image-name:
        description: |
          Name of the docker image to be deployed
        type: string
      version-info:
        description: |
          App version information
        type: string
      aws-region:
        description: |
          AWS region
        type: string
        default: ""
    steps:
      - checkout
      - run:
          name: Create deployment manifest
          command: |
            BUILD_DATE=$(date '+%Y%m%d%H%M%S')
            cat deployment/demo-app-deployment.yaml | \
                sed "s|DOCKER_IMAGE_NAME|<< parameters.docker-image-name >> | \
                g;s|BUILD_DATE_VALUE|$BUILD_DATE|g;s|VERSION_INFO_VALUE| \
                << parameters.version-info >>|g" > deployment/demo-app-deployment.yaml




workflows:
  deployment:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL # 773075230823.dkr.ecr.us-east-1.amazonaws.com
          repo: circleci-kubernetes-docker-flask
          dockerfile: Dockerfile
          path: demo_app
          tag: ${CIRCLE_SHA1}

      # - aws-eks/create-cluster:
      #     cluster-name: eks-app-deployment
      #     aws-region: $AWS_REGION 
      #     requires:
      #       - aws-ecr/build-and-push-image
      
      - deploy-application:
          cluster-name: eks-app-deployment
          aws-region: $AWS_REGION 
          docker-image-name: ""
          version-info: "${CIRCLE_SHA1}"
          requires:
            - aws-ecr/build-and-push-image


      # - aws-eks/delete-cluster:
      #     cluster-name: eks-app-deployment
      #     aws-region: $AWS_REGION 
      #     wait: true 
      #     requires:
      #       - aws-eks/create-cluster