jobs:
  run-install-eksctl:
    executor: circleci/python:3.7
    
    steps:
      - checkout
      - run:
          name: Install the eksctl tool
          command: |
            if which eksctl > /dev/null; then
              echo "eksctl is already installed"
              exit 0
            fi
            mkdir -p eksctl_download
            curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
              | tar xz -C eksctl_download
            chmod +x eksctl_download/eksctl
            SUDO=""
            if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
              SUDO="sudo"
            fi
            $SUDO mv eksctl_download/eksctl /usr/local/bin/
            rmdir eksctl_download


version: 2.1
orbs:
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.4.0
  aws-ecr: circleci/aws-ecr@7.2.0

workflows:
  deployment:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL # 773075230823.dkr.ecr.us-east-1.amazonaws.com
          repo: circleci-kubernetes-docker-flask
          dockerfile: Dockerfile
          path: demo_app
          tag: ${CIRCLE_SHA1}
      
      - run-install-eksctl

      - aws-eks/create-cluster:
          cluster-name: eks-app-deployment
          aws-region: $AWS_REGION 
          requires:
            - aws-ecr/build-and-push-image