version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.0.0
  kubernetes: circleci/kubernetes@1.0.0
  aws-ecr: circleci/aws-ecr@7.2.1

workflows:
  deployment:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL # 773075230823.dkr.ecr.us-east-1.amazonaws.com
          repo: circleci-kubernetes-docker-flask
          dockerfile: Dockerfile
          path: demo_app
          tag: ${CIRCLE_SHA1}

      - aws-eks/create-cluster:
          cluster-name: eks-app-deployment
          aws-region: $AWS_REGION 
          requires:
            - aws-ecr/build-and-push-image